apiVersion: "apps/v1beta1"
kind: "Deployment"
metadata:
  name: "hello"
  labels:
    app: "hello"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "hello"
    spec:
      containers:
      - name: "hello"
        image: "sdomula/hello:v1.0.0"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: "/healthz"
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 8080
