{{- if .Values.service.enabled -}}
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ .Chart.Name | quote }}
  labels:
    app:  {{ .Chart.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: "NodePort"
  selector:
    app: {{ .Chart.Name | quote }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: {{ .Values.service.port }}
{{- end -}}
